<?php
/**
 * Copyright (c) 2024
 * MIT License
 * Module AnassTouatiCoder_OutdatedBrowserNotifier
 * Author Anass TOUATI anass1touati@gmail.com
 */
?>

<script>
    var $buoop = {required:{e:-3,f:-3,o:-3,s:-3,c:-3},insecure:true,unsupported:true,api:2024.05 };
    function $buo_f(){
        var e = document.createElement("script");
        e.src = "//browser-update.org/update.min.js";
        document.body.appendChild(e);
    };
    try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
    catch(e){window.attachEvent("onload", $buo_f)}
</script>
